### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by odidev** [ewindisch/docker-cirros#5]
Cirros requires rootfs for ```ARM64``` architecture.

I have done changes at my end, which will fetch ```ARM64/X86``` rootfs based on host architecture and create Docker correspondingly.

I have verified working of this on ARM64, and I would be happy to raise PR with the changes required.

**Comment by tianon** [comment]
There's some past discussion on this topic over in https://github.com/ewindisch/docker-cirros/issues/4 too.

**Comment by odidev** [comment]
**Closing** this issue as ```Cirros``` is now officially supporting ```arm64v8```.
Thanks for your support.
